services:
  api:
    image: camilo192/devops-project-api:latest
    ports: 
      - "8000:8000"
    # Aqu√≠ mapeas las variables del sistema/archivo .env al contenedor
    environment:
      - AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_KEY}
  
  frontend:
    image: camilo192/devops-project-frontend:latest
    ports:
      - "80:80"