name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    #These lines help only to make a push when the source code for the bakcend of front end has changed
    paths:
      # Explicitly watch all source files in the main application directories
      - 'api/**'
      - 'front-end-nextjs/**'
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build . /api/ -t camilo192/devops-project-frontend:latest
          docker build . /front-end-nextjs/ -t camilo192/devops-project-backend:latest
      - name: push image to docker hub
        run: |
          docker login -u camilo192 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push camilo192/devops-project-frontend:latest
          docker push camilo192/devops-project-backtend:latest